name: ESP-IDF Build CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build Firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: 'v6.0.2'
          target: 'esp32s3'
          path: '.'